import { useState } from "react";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { Eye, Trash2 } from "lucide-react";
import { DeleteConfirmDialog } from "../shared/DeleteConfirmDialog";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";

const mockReports = [
  { id: "1", title: "Monthly User Activity", type: "Activity", date: "2024-01-15", status: "Completed" },
  { id: "2", title: "Course Completion Analysis", type: "Performance", date: "2024-01-14", status: "Completed" },
  { id: "3", title: "Revenue Report Q4 2023", type: "Financial", date: "2024-01-10", status: "Completed" },
  { id: "4", title: "System Health Check", type: "System", date: "2024-01-08", status: "Completed" },
];

export function ReportsTable() {
  const [reports, setReports] = useState(mockReports);
  const [viewingReport, setViewingReport] = useState<any>(null);
  const [deletingReport, setDeletingReport] = useState<any>(null);

  const handleDeleteReport = () => {
    setReports(reports.filter(r => r.id !== deletingReport.id));
    setDeletingReport(null);
  };

  return (
    <div className="space-y-4">
      <div className="border rounded-lg">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Title</TableHead>
              <TableHead>Type</TableHead>
              <TableHead>Date</TableHead>
              <TableHead>Status</TableHead>
              <TableHead className="text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {reports.map((report) => (
              <TableRow key={report.id}>
                <TableCell className="font-medium">{report.title}</TableCell>
                <TableCell>{report.type}</TableCell>
                <TableCell>{report.date}</TableCell>
                <TableCell>
                  <span className="px-2 py-1 rounded-full text-xs bg-green-100 text-green-800">
                    {report.status}
                  </span>
                </TableCell>
                <TableCell className="text-right">
                  <Button
                    variant="ghost"
                    size="icon"
                    onClick={() => setViewingReport(report)}
                  >
                    <Eye className="h-4 w-4" />
                  </Button>
                  <Button
                    variant="ghost"
                    size="icon"
                    onClick={() => setDeletingReport(report)}
                  >
                    <Trash2 className="h-4 w-4 text-destructive" />
                  </Button>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>

      <Dialog open={!!viewingReport} onOpenChange={(open) => !open && setViewingReport(null)}>
        <DialogContent className="max-w-3xl">
          <DialogHeader>
            <DialogTitle>{viewingReport?.title}</DialogTitle>
            <DialogDescription>
              {viewingReport?.type} Report • {viewingReport?.date}
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            <p className="text-muted-foreground">
              This is a mock report view. In a real application, this would display the full report content,
              charts, and data tables.
            </p>
            <div className="bg-muted p-4 rounded-lg">
              <h3 className="font-semibold mb-2">Report Summary</h3>
              <ul className="list-disc list-inside space-y-1 text-sm">
                <li>Total records analyzed: 1,234</li>
                <li>Time period: Last 30 days</li>
                <li>Generated by: System Admin</li>
                <li>Status: All checks passed</li>
              </ul>
            </div>
          </div>
        </DialogContent>
      </Dialog>

      <DeleteConfirmDialog
        open={!!deletingReport}
        onOpenChange={(open) => !open && setDeletingReport(null)}
        onConfirm={handleDeleteReport}
        title="Delete Report"
        description={`Are you sure you want to delete "${deletingReport?.title}"? This action cannot be undone.`}
      />
    </div>
  );
}
